version: '3.8'
services:  
  api:    
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener_backend
    ports:      
      - '3000:3000'    
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
